const styles = {
  root: { fontFamily: "'Georgia', 'Times New Roman', serif", background: "#0d0f10", color: "#e8e4dc", minHeight: "100vh", display: "flex", flexDirection: "column" },
  nav: { background: "#111316", borderBottom: "1px solid #222", position: "sticky", top: 0, zIndex: 100 },
  navInner: { maxWidth: 1100, margin: "0 auto", padding: "0 24px", height: 64, display: "flex", alignItems: "center", justifyContent: "space-between" },
  logo: { display: "flex", alignItems: "center", gap: 8, cursor: "pointer", userSelect: "none" },
  logoIcon: { fontSize: 22, color: "#d97706" },
  logoText: { fontSize: 22, fontWeight: "bold", letterSpacing: "-0.5px", color: "#e8e4dc" },
  logoAccent: { color: "#d97706" },
  navLinks: { display: "flex", alignItems: "center", gap: 8 },
  navLink: { background: "none", border: "none", color: "#9a9490", cursor: "pointer", padding: "8px 14px", fontSize: 15, borderRadius: 6, fontFamily: "inherit" },
  navLinkActive: { background: "none", border: "none", color: "#e8e4dc", cursor: "pointer", padding: "8px 14px", fontSize: 15, borderRadius: 6, fontFamily: "inherit", fontWeight: "bold" },
  navCTA: { background: "#d97706", border: "none", color: "#0d0f10", cursor: "pointer", padding: "8px 18px", fontSize: 14, borderRadius: 6, fontWeight: "bold", fontFamily: "inherit", marginLeft: 8 },
  main: { flex: 1, maxWidth: 1100, margin: "0 auto", padding: "0 24px 60px", width: "100%", boxSizing: "border-box" },
  notifWrap: { margin: "0 0 16px" },
  notifBanner: { background: "#2a1a08", border: "1px solid #d97706", borderRadius: 8, padding: "12px 16px", fontSize: 14, color: "#d97706", marginBottom: 8 },
  hero: { padding: "72px 0 48px", borderBottom: "1px solid #1e2022", marginBottom: 36 },
  heroBadge: { display: "inline-block", background: "#1a1408", border: "1px solid #3a2a08", color: "#d97706", fontSize: 12, letterSpacing: "0.08em", textTransform: "uppercase", padding: "4px 12px", borderRadius: 20, marginBottom: 20 },
  heroTitle: { fontSize: 52, fontWeight: "bold", lineHeight: 1.1, margin: "0 0 16px", letterSpacing: "-1px" },
  heroAccent: { color: "#d97706" },
  heroSub: { fontSize: 18, color: "#9a9490", maxWidth: 480, lineHeight: 1.6, margin: "0 0 28px" },
  heroActions: { display: "flex", gap: 12 },
  btnPrimary: { background: "#d97706", border: "none", color: "#0d0f10", padding: "12px 24px", fontSize: 15, fontWeight: "bold", borderRadius: 6, cursor: "pointer", fontFamily: "inherit" },
  btnSecondary: { background: "transparent", border: "1px solid #333", color: "#e8e4dc", padding: "12px 24px", fontSize: 15, borderRadius: 6, cursor: "pointer", fontFamily: "inherit" },
  filterBar: { display: "flex", alignItems: "center", gap: 12, marginBottom: 28, flexWrap: "wrap" },
  filterSelect: { background: "#161819", border: "1px solid #2a2c2e", color: "#e8e4dc", padding: "9px 14px", borderRadius: 6, fontSize: 14, fontFamily: "inherit", minWidth: 200 },
  filterInput: { background: "#161819", border: "1px solid #2a2c2e", color: "#e8e4dc", padding: "9px 14px", borderRadius: 6, fontSize: 14, fontFamily: "inherit", minWidth: 200, outline: "none" },
  filterCount: { color: "#6a6660", fontSize: 13, marginLeft: "auto" },
  cardGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))", gap: 20 },
  jobCard: { background: "#111316", border: "1px solid #1e2022", borderRadius: 10, padding: "20px 22px", cursor: "pointer" },
  cardTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 10 },
  cardCompany: { fontSize: 12, color: "#7a7570", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 4 },
  cardTitle: { fontSize: 18, fontWeight: "bold", color: "#e8e4dc", lineHeight: 1.3 },
  cardBadge: { background: "#1a2a1a", color: "#4ade80", fontSize: 11, padding: "3px 9px", borderRadius: 12, whiteSpace: "nowrap", marginLeft: 10 },
  availBadge: { fontSize: 11, padding: "3px 10px", borderRadius: 12, whiteSpace: "nowrap", marginLeft: 10 },
  cardMeta: { display: "flex", gap: 16, fontSize: 13, color: "#7a7570", marginBottom: 14, flexWrap: "wrap" },
  certSection: { marginBottom: 14 },
  certLabel: { fontSize: 11, color: "#6a6660", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 4, marginTop: 6 },
  certTags: { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 4 },
  certTag: { fontSize: 11, padding: "3px 9px", borderRadius: 4, color: "#e8e4dc", letterSpacing: "0.04em" },
  cardFooter: { display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 8 },
  cardPosted: { fontSize: 12, color: "#555" },
  cardLink: { fontSize: 13, color: "#d97706", fontWeight: "bold" },
  techSummary: { fontSize: 13, color: "#8a8580", lineHeight: 1.5, margin: "8px 0 14px" },
  detailWrap: { paddingTop: 32 },
  backBtn: { background: "none", border: "none", color: "#d97706", cursor: "pointer", fontSize: 14, padding: "0 0 20px", fontFamily: "inherit", display: "block" },
  detailCard: { background: "#111316", border: "1px solid #1e2022", borderRadius: 12, padding: "32px 36px", maxWidth: 720 },
  detailHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 20 },
  detailTitle: { fontSize: 28, fontWeight: "bold", margin: "4px 0 10px", letterSpacing: "-0.5px" },
  divider: { height: 1, background: "#1e2022", margin: "20px 0" },
  sectionLabel: { fontSize: 12, textTransform: "uppercase", letterSpacing: "0.1em", color: "#6a6660", margin: "16px 0 10px" },
  detailDesc: { fontSize: 15, color: "#b0aca6", lineHeight: 1.7, margin: "0 0 24px" },
  qualGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 16 },
  qualItem: { background: "#0d0f10", border: "1px solid #1e2022", borderRadius: 6, padding: "10px 14px", display: "flex", justifyContent: "space-between", alignItems: "center" },
  qualLabel: { fontSize: 13, color: "#8a8580" },
  qualYes: { fontSize: 13, color: "#4ade80" },
  qualNo: { fontSize: 13, color: "#555" },
  pageHeader: { padding: "48px 0 32px", borderBottom: "1px solid #1e2022", marginBottom: 36 },
  pageTitle: { fontSize: 36, fontWeight: "bold", margin: "0 0 8px", letterSpacing: "-0.5px" },
  pageSub: { fontSize: 15, color: "#7a7570", margin: 0 },
  inlineLink: { color: "#d97706", textDecoration: "none" },
  formWrap: { paddingTop: 32, maxWidth: 640 },
  successCard: { background: "#111316", border: "1px solid #1e2022", borderRadius: 12, padding: "48px 40px", textAlign: "center", maxWidth: 480, marginTop: 32 },
  successIcon: { fontSize: 48, marginBottom: 16 },
  successTitle: { fontSize: 28, fontWeight: "bold", margin: "0 0 16px", letterSpacing: "-0.5px" },
  successMsg: { fontSize: 15, color: "#9a9490", lineHeight: 1.7, margin: "0 0 28px" },
  formCard: { background: "#111316", border: "1px solid #1e2022", borderRadius: 12, padding: "36px 40px" },
  formSteps: { display: "flex", gap: 8, marginBottom: 28 },
  step: { width: 30, height: 30, borderRadius: "50%", background: "#1e2022", color: "#555", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: "bold" },
  stepActive: { background: "#d97706", color: "#0d0f10" },
  formTitle: { fontSize: 24, fontWeight: "bold", margin: "0 0 24px", letterSpacing: "-0.3px" },
  formFields: { display: "flex", flexDirection: "column", gap: 12 },
  label: { fontSize: 13, color: "#8a8580", marginBottom: 2, letterSpacing: "0.04em" },
  input: { background: "#0d0f10", border: "1px solid #2a2c2e", borderRadius: 6, color: "#e8e4dc", padding: "10px 14px", fontSize: 15, fontFamily: "inherit", outline: "none", width: "100%", boxSizing: "border-box" },
  textarea: { background: "#0d0f10", border: "1px solid #2a2c2e", borderRadius: 6, color: "#e8e4dc", padding: "10px 14px", fontSize: 15, fontFamily: "inherit", outline: "none", width: "100%", boxSizing: "border-box", minHeight: 100, resize: "vertical" },
  certGrid: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 4 },
  certToggle: { background: "#0d0f10", border: "1px solid #2a2c2e", borderRadius: 6, color: "#8a8580", padding: "7px 13px", fontSize: 13, cursor: "pointer", userSelect: "none" },
  certToggleActive: { background: "#1a2a08", border: "1px solid #4ade80", color: "#4ade80" },
  qualBlock: { background: "#0d0f10", border: "1px solid #2a2c2e", borderRadius: 8, padding: "14px 16px", display: "flex", flexDirection: "column", gap: 8 },
  qualRow: { display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 8 },
  qualBlockLabel: { fontSize: 14, color: "#e8e4dc" },
  yesNoRow: { display: "flex", gap: 6, flexShrink: 0 },
  yesNoBtn: { background: "#1a1c1e", border: "1px solid #2a2c2e", color: "#6a6660", padding: "5px 14px", borderRadius: 6, cursor: "pointer", fontSize: 13, fontFamily: "inherit", whiteSpace: "nowrap", minWidth: 44, textAlign: "center", flexShrink: 0 },
  yesNoBtnActive: { background: "#1a4a2e", border: "1px solid #4ade80", color: "#4ade80" },
  yesNoBtnNo: { background: "#2a1a1a", border: "1px solid #555", color: "#aaa" },
  subField: { paddingTop: 8, display: "flex", flexDirection: "column", gap: 8 },
  errorMsg: { background: "#2a0a0a", border: "1px solid #8B0000", borderRadius: 6, padding: "8px 12px", fontSize: 13, color: "#ff6b6b" },
  warnMsg: { background: "#2a1a08", border: "1px solid #d97706", borderRadius: 6, padding: "8px 12px", fontSize: 13, color: "#d97706" },
  uploadBox: { border: "2px dashed #2a2c2e", borderRadius: 8, padding: "20px", textAlign: "center", display: "flex", flexDirection: "column", alignItems: "center", gap: 6, cursor: "pointer" },
  uploadIcon: { fontSize: 24 },
  uploadText: { fontSize: 13, color: "#8a8580", margin: 0 },
  uploadSub: { fontSize: 12, color: "#555", margin: "0 0 8px" },
  formRow: { display: "flex", gap: 12, justifyContent: "flex-end" },
  toggleRow: { display: "flex", alignItems: "center", justifyContent: "space-between", background: "#0d0f10", border: "1px solid #2a2c2e", borderRadius: 8, padding: "16px 18px" },
  toggleInfo: { flex: 1 },
  toggleTitle: { fontSize: 15, fontWeight: "bold", marginBottom: 4 },
  toggleSub: { fontSize: 13, color: "#6a6660", lineHeight: 1.4 },
  toggleSwitch: { width: 50, height: 26, borderRadius: 13, cursor: "pointer", position: "relative", transition: "background 0.2s", flexShrink: 0, marginLeft: 16 },
  toggleKnob: { position: "absolute", top: 3, left: 3, width: 20, height: 20, borderRadius: "50%", background: "#fff", transition: "transform 0.2s" },
  availNote: { background: "#0d0f10", border: "1px solid #2a2c2e", borderRadius: 6, padding: "12px 16px", fontSize: 14, color: "#8a8580" },
  certInstructions: { fontSize: 13, color: "#8a8580", margin: "0 0 8px", lineHeight: 1.5 },
  certRequireRow: { display: "flex", justifyContent: "space-between", alignItems: "center", background: "#0d0f10", border: "1px solid #1e2022", borderRadius: 6, padding: "10px 14px" },
  certRequireLabel: { fontSize: 14, color: "#e8e4dc" },
  reqBtn: { background: "#1a1c1e", border: "1px solid #2a2c2e", color: "#6a6660", padding: "4px 10px", borderRadius: 6, cursor: "pointer", fontSize: 12, fontFamily: "inherit" },
  reqBtnRequired: { background: "#2a0a0a", border: "1px solid #8B0000", color: "#ff6b6b" },
  reqBtnPreferred: { background: "#0a1a2a", border: "1px solid #1a3a5a", color: "#7ab3d4" },
  reviewCard: { background: "#0d0f10", border: "1px solid #2a2c2e", borderRadius: 8, padding: "18px 20px", marginBottom: 20 },
  reviewRow: { display: "flex", justifyContent: "space-between", padding: "7px 0", borderBottom: "1px solid #1a1c1e", fontSize: 14 },
  reviewLabel: { color: "#6a6660" },
  pricingBox: { background: "#12100a", border: "1px solid #3a2a08", borderRadius: 10, padding: "22px 24px", marginBottom: 20 },
  pricingTitle: { fontSize: 12, textTransform: "uppercase", letterSpacing: "0.08em", color: "#d97706", marginBottom: 6 },
  pricingAmount: { fontSize: 36, fontWeight: "bold", marginBottom: 14, letterSpacing: "-1px" },
  pricingPer: { fontSize: 16, fontWeight: "normal", color: "#6a6660" },
  pricingFeatures: { listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 6, fontSize: 14, color: "#9a9490" },
  footer: { borderTop: "1px solid #1a1c1e", padding: "24px" },
  footerInner: { maxWidth: 1100, margin: "0 auto", display: "flex", alignItems: "center", gap: 16 },
  footerSub: { fontSize: 13, color: "#555" },
};

export default styles;
